# Generated by Django 5.2.1 on 2025-06-17 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("watchlist_app", "0006_watchlist_avg_rating_watchlist_number_rating"),
    ]

    operations = [
        migrations.RenameField(
            model_name="review",
            old_name="created_at",
            new_name="created",
        ),
        migrations.RenameField(
            model_name="watchlist",
            old_name="created_at",
            new_name="created",
        ),
    ]
